name: inventories_data_source
description: A generic interface for managing inventories.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.16.0
