name: in_memory_inventories_data_source
description: An in-memory implementation of the InventoriesDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  inventories_data_source:
    path: ../inventories_data_source
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
